services:
  web:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - $PWD/rabbitmq/data:/var/lib/rabbitmq
      - $PWD/rabbitmq/log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"