services:
  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - pgvector
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/ssl:/etc/nginx/certs:ro

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin_1234_qwer
      - POSTGRES_DB=db
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - $PWD/postgres/db/:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/data:/data
